language: python

python:
    - "2.6"
    - "2.7"
script:
    - python helloworld.py
notifications:
    recipients:
        - wengcc@ihep.ac.cn
    on_success: change
    on_failure: always
    irc:
        channels:
            - "irc.freenode.org#cloudsafe"
        on_success: change
        on_failure: always
